### ISSUE TITLE
Problem to install

### ISSUE THREAD

**Issue by lucasinocente** [s-a/iso-8583#11]
Hi! I'm have this problem when I try to install the package with `npm install iso-8583`

```
> iso-8583@1.0.7 install C:\Projetos\bit-validator\validator\node_modules\iso-8583
> node-gyp rebuild

C:\Projetos\bit-validator\validator\node_modules\iso-8583>if not defined npm_config_node_gyp (node "C:\Users\Datum\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Datum\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  NativeExtension.cc
  functions.cc
  win_delay_load_hook.cc
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Cannot open include file: 'ctype.h':
 No such file or directory (compiling source file C:\Users\Datum\AppData\Roaming\npm\node_modules\npm\node_modules\node
-gyp\src\win_delay_load_hook.cc) [C:\Projetos\bit-validator\validator\node_modules\iso-8583\build\ISO8583.vcxproj]
c:\users\datum\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include file: 'errno.h': No
 such file or directory (compiling source file ..\functions.cc) [C:\Projetos\bit-validator\validator\node_modules\iso-8
583\build\ISO8583.vcxproj]
c:\users\datum\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include file: 'errno.h': No
 such file or directory (compiling source file ..\NativeExtension.cc) [C:\Projetos\bit-validator\validator\node_modules
\iso-8583\build\ISO8583.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Datum\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Datum\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Projetos\bit-validator\validator\node_modules\iso-8583
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN bit-validator@1.0.0 No description
npm WARN bit-validator@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iso-8583@1.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iso-8583@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Datum\AppData\Roaming\npm-cache\_logs\2018-07-31T22_17_07_850Z-debug.log

```

What i'm doing wrong?

**Comment by hamzachar** [comment]
Hi @lucasinocente did you resolve this issue?  Can you please give some help, I'm facing the same problem :/

**Comment by hamzachar** [comment]
Pleaaase.... Does anyone have any idea about this issue? 

`C:\Users\user\Desktop\NodeAppTest\ISO8583 2>npm install iso-8583

> iso-8583@1.0.7 install C:\Users\user\Desktop\NodeAppTest\ISO8583 2\node_modules\iso-8583
> node-gyp rebuild


C:\Users\user\Desktop\NodeAppTest\ISO8583 2\node_modules\iso-8583>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2004, in GenerateOutput
    generator_flags))
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 941, in _GenerateProject
    return _GenerateMSBuildProject(project, options, version, generator_flags)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 3309, in _GenerateMSBuildProject
    extension_to_rule_name)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2061, in _GenerateMSBuildFiltersFile
    easy_xml.WriteXmlIfChanged(content, filters_path, pretty=True, win32=True)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\easy_xml.py", line 134, in WriteXmlIfChanged
    f = open(path, 'w')
IOError: [Errno 2] No such file or directory: 'C:\\Users\\user\\Desktop\\NodeAppTest\\ISO8583 2\\node_modules\\iso-8583\\build\\ISO8583.vcxproj.filters'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\Desktop\NodeAppTest\ISO8583 2\node_modules\iso-8583
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\user\Desktop\NodeAppTest\ISO8583 2\package.json'
npm WARN ISO8583 2 No description
npm WARN ISO8583 2 No repository field.
npm WARN ISO8583 2 No README data
npm WARN ISO8583 2 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iso-8583@1.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iso-8583@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-10-04T15_22_10_365Z-debug.log`

**Comment by lucasinocente** [comment]
sorry dude, I give up and use another lib https://github.com/zemuldo/iso_8583
